<#
.SYNOPSIS
    upgrade_ - kickstart generator: job.json -> ks.cfg (Fedora).

.DESCRIPTION
    The per-target seam (architecture.md, build order step 3). Everything the
    installer needs to run with no human present comes from job.json; this
    script turns it into text and nothing else - it reads no hardware and
    decides nothing. The one thing it cannot know is the Linux name of the
    disk the job identifies, so the storage section is a %include written at
    boot time by upgrade_/linux/verify.sh, which resolves the disk by the
    identity in the job (serial, unique id, size) and refuses on a mismatch.

    The same kickstart serves both halves of the vertical: with
    upg.mode=verify on the kernel command line, verify.sh reports and reboots
    inside %pre and the install never starts (the reversible half); without
    it, %pre resolves storage and the install proceeds (the destructive half).

.PARAMETER JobPath
    job.json (schema job/1). A job whose schema string is not exactly job/1
    is refused - a reader that meets a version it does not understand must
    refuse, not guess.

.PARAMETER OutFile
    Where to write ks.cfg. Omit to print.

.PARAMETER StickLabel
    Volume label of the stick the installer boots from (default UPGV0).
#>
[CmdletBinding()]
param(
    [string]$JobPath,
    [string]$OutFile,
    [string]$StickLabel = 'UPGV0',
    [switch]$SelfTest
)
$ErrorActionPreference = 'Stop'
$KsGenVersion = '0.1.0'

function Test-KsJob {
    # The shape checks a PS 5.1 host can do without a JSON Schema validator:
    # the version string, the top-level blocks, and the fields the text below
    # actually uses. schemas/check.py is the real validator; this is the
    # refusal at the point of use.
    param($Job)
    if ($Job.schema -ne 'job/1') { throw "job schema '$($Job.schema)' is not job/1; refusing to generate" }
    foreach ($k in @('job_id', 'identity', 'intent', 'fork', 'storage', 'harvest', 'stick')) {
        if (-not $Job.PSObject.Properties[$k]) { throw "job.json lacks '$k'; refusing" }
    }
    if ($Job.intent.path -notin @('keep-windows', 'clean-slate')) { throw "intent.path '$($Job.intent.path)' is not a path" }
    if ($Job.intent.desktop -notin @('kde', 'gnome')) { throw "intent.desktop '$($Job.intent.desktop)' is not kde or gnome" }
    if ($Job.intent.account.password_hash -notmatch '^\$6\$') { throw 'account.password_hash is not SHA-512 crypt; refusing' }
    if ($Job.intent.account.linux_name -notmatch '^[a-z_][a-z0-9_-]{0,31}$') { throw "linux_name '$($Job.intent.account.linux_name)' is not a login name" }
    if (-not $Job.intent.locale.lang -or -not $Job.intent.locale.timezone -or -not $Job.intent.locale.keymap) { throw 'locale is incomplete' }
    if ($Job.intent.distro.name -ne 'fedora') { throw "distro '$($Job.intent.distro.name)' has no generator" }
}

function ConvertTo-KsQuoted {
    # kickstart double-quoted value; the only character that needs care is "
    param([string]$s)
    '"' + ($s -replace '"', '\"') + '"'
}

function New-Kickstart {
    param($Job, [string]$Label)
    Test-KsJob -Job $Job
    $i = $Job.intent
    $L = New-Object System.Collections.Generic.List[string]
    $L.Add("# upgrade_ kickstart - generated by New-Kickstart.ps1 $KsGenVersion")
    $L.Add("# job: $($Job.job_id)   path: $($i.path)   desktop: $($i.desktop)   machine: $($Job.identity.vendor) $($Job.identity.model)")
    $L.Add("# Do not edit: the converter regenerates this from job.json. The storage")
    $L.Add("# section is written at boot by upgrade_/linux/verify.sh after it has")
    $L.Add("# matched this machine's disk against the identity in the job.")
    $L.Add('text')
    $L.Add("lang $($i.locale.lang)")
    $L.Add("keyboard --xlayouts='$($i.locale.keymap)'")
    $L.Add("timezone $($i.locale.timezone) --utc")
    $L.Add('rootpw --lock')
    $gecos = if ($i.account.full_name) { " --gecos=$(ConvertTo-KsQuoted $i.account.full_name)" } else { '' }
    $L.Add("user --name=$($i.account.linux_name)$gecos --iscrypted --password=$($i.account.password_hash) --groups=wheel")
    $L.Add('network --bootproto=dhcp --device=link --activate --hostname=fedora')
    $L.Add('selinux --enforcing')
    $L.Add('firewall --enabled')
    $L.Add('services --enabled=NetworkManager')
    $L.Add('')
    $L.Add('# identity + hardware verification, then the storage %include. With')
    $L.Add('# upg.mode=verify on the command line this reports and reboots - no install.')
    $L.Add('%pre --log=/tmp/upgrade_-pre.log --erroronfail')
    $L.Add("exec /bin/bash /run/install/repo/upgrade_/verify.sh /run/install/repo/upgrade_/job.json $Label")
    $L.Add('%end')
    $L.Add('')
    $L.Add('%include /tmp/upgrade_-storage.ks')
    $L.Add('')
    $L.Add('# offline: the desktop image travels on the stick (architecture.md, "Design constraint: offline")')
    $L.Add("liveimg --url=file:///run/install/repo/upgrade_/LiveOS/$($i.desktop).squashfs")
    $L.Add('')
    $L.Add('reboot')
    $L.Add('')
    $L.Add('%post --log=/root/upgrade_-post.log')
    $L.Add('set -x')
    if ($i.path -eq 'keep-windows') {
        $L.Add('# keep-windows: Windows appears in the menu by our doing, not by luck (RISKS R21)')
        $L.Add("if grep -q '^GRUB_DISABLE_OS_PROBER=' /etc/default/grub; then sed -i 's/^GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER=false/' /etc/default/grub; else echo 'GRUB_DISABLE_OS_PROBER=false' >> /etc/default/grub; fi")
        $L.Add('grub2-mkconfig -o /boot/grub2/grub.cfg')
        $L.Add("grep -c -i windows /boot/grub2/grub.cfg > /root/upgrade_-grub-windows-entries.txt || true")
    }
    $L.Add('efibootmgr -v > /root/upgrade_-efibootmgr.txt 2>&1 || true')
    $L.Add('%end')
    ($L -join "`n") + "`n"
}

function Invoke-SelfTest {
    $ex = Join-Path $PSScriptRoot '..\..\schemas\examples'
    $keep  = Get-Content (Join-Path $ex 'job.keep-windows.json') -Raw | ConvertFrom-Json
    $clean = Get-Content (Join-Path $ex 'job.clean-slate.json') -Raw | ConvertFrom-Json
    $ksK = New-Kickstart -Job $keep -Label 'UPGV0'
    $ksC = New-Kickstart -Job $clean -Label 'UPGV0'
    $cases = @(
        @{ Name = 'keep-windows example generates'; Run = { [bool]$ksK }; Expect = $true }
        @{ Name = 'clean-slate example generates'; Run = { [bool]$ksC }; Expect = $true }
        @{ Name = 'lang, keymap, timezone come from intent.locale'
           Run = { ($ksK -match "(?m)^lang en_US\.UTF-8$") -and ($ksK -match "(?m)^keyboard --xlayouts='us'$") -and ($ksK -match "(?m)^timezone America/New_York --utc$") }; Expect = $true }
        @{ Name = 'the password hash passes through untouched and root is locked'
           Run = { ($ksK -match [regex]::Escape("--iscrypted --password=$($keep.intent.account.password_hash) --groups=wheel")) -and ($ksK -match '(?m)^rootpw --lock$') }; Expect = $true }
        @{ Name = 'the desktop selects the squashfs'
           Run = { ($ksK -match '(?m)^liveimg --url=file:///run/install/repo/upgrade_/LiveOS/kde\.squashfs$') -and ($ksC -match 'gnome\.squashfs') }; Expect = $true }
        @{ Name = 'storage is a %include the verifier writes, never inline'
           Run = { ($ksK -match '(?m)^%include /tmp/upgrade_-storage\.ks$') -and ($ksK -notmatch '(?m)^(part|clearpart|ignoredisk|autopart) ') }; Expect = $true }
        @{ Name = '%pre runs verify.sh with the job and the stick label, erroring on failure'
           Run = { ($ksK -match '(?m)^%pre --log=/tmp/upgrade_-pre\.log --erroronfail$') -and ($ksK -match '(?m)verify\.sh /run/install/repo/upgrade_/job\.json UPGV0$') }; Expect = $true }
        @{ Name = 'keep-windows %post turns os-prober on; clean-slate does not'
           Run = { ($ksK -match 'GRUB_DISABLE_OS_PROBER=false') -and ($ksC -notmatch 'OS_PROBER') }; Expect = $true }
        @{ Name = 'a full name becomes --gecos, quoted'
           Run = { $ksK -match '--gecos="Addison Example"' }; Expect = $true }
        @{ Name = 'no full name, no --gecos'
           Run = { $ksC -notmatch '--gecos' }; Expect = $true }
        @{ Name = 'refuse: schema job/2'
           Run = { $j = $keep | ConvertTo-Json -Depth 10 | ConvertFrom-Json; $j.schema = 'job/2'; try { New-Kickstart -Job $j -Label 'X' | Out-Null; 'accepted' } catch { 'refused' } }; Expect = 'refused' }
        @{ Name = 'refuse: cleartext password'
           Run = { $j = $keep | ConvertTo-Json -Depth 10 | ConvertFrom-Json; $j.intent.account.password_hash = 'hunter2'; try { New-Kickstart -Job $j -Label 'X' | Out-Null; 'accepted' } catch { 'refused' } }; Expect = 'refused' }
        @{ Name = 'refuse: a login name with a space'
           Run = { $j = $keep | ConvertTo-Json -Depth 10 | ConvertFrom-Json; $j.intent.account.linux_name = 'john smith'; try { New-Kickstart -Job $j -Label 'X' | Out-Null; 'accepted' } catch { 'refused' } }; Expect = 'refused' }
        @{ Name = 'refuse: a distro with no generator'
           Run = { $j = $keep | ConvertTo-Json -Depth 10 | ConvertFrom-Json; $j.intent.distro.name = 'ubuntu'; try { New-Kickstart -Job $j -Label 'X' | Out-Null; 'accepted' } catch { 'refused' } }; Expect = 'refused' }
        @{ Name = 'output uses LF line endings only (the installer reads it on Linux)'
           Run = { -not $ksK.Contains("`r") }; Expect = $true }
    )
    $failed = 0
    Write-Host ''; Write-Host "  upgrade_  kickstart generator $KsGenVersion  -  SELF-TEST" -ForegroundColor Cyan; Write-Host ''
    foreach ($c in $cases) {
        $got = & $c.Run
        if ("$got" -eq "$($c.Expect)") { Write-Host "    PASS  $($c.Name)" -ForegroundColor Green }
        else { Write-Host "    FAIL  $($c.Name)  (expected '$($c.Expect)', got '$got')" -ForegroundColor Red; $failed++ }
    }
    Write-Host ''
    if ($failed -gt 0) { Write-Host "  $failed check(s) failed" -ForegroundColor Red; exit 1 }
    Write-Host '  all checks passed' -ForegroundColor Green; Write-Host ''
}

if ($SelfTest) { Invoke-SelfTest; return }
if (-not $JobPath) { throw 'give -JobPath job.json (or -SelfTest)' }
$job = Get-Content -LiteralPath $JobPath -Raw | ConvertFrom-Json
$ks = New-Kickstart -Job $job -Label $StickLabel
if ($OutFile) {
    [IO.File]::WriteAllText($OutFile, $ks, (New-Object Text.UTF8Encoding($false)))
    Write-Host "  wrote $OutFile ($($ks.Length) bytes) for job $($job.job_id)"
} else { $ks }
