//! The Rust kickstart generator against New-Kickstart.ps1 (RISKS R32;
//! VALIDATION V13). `cases.json` lists the inputs: the PowerShell
//! self-test's cases under their own names, plus inputs for every refusal
//! and the manifest's edges. `golden.json` is what the PowerShell produced
//! (written by `golden.ps1`). The text must be equal from the second line
//! on; the first line names the generator and differs on purpose.

use serde_json::Value;
use std::path::PathBuf;
use upgrade_kickstart::{kickstart, kickstart_for};
use upgrade_schema::Job;

fn cases() -> Vec<Value> {
    serde_json::from_str(include_str!("cases.json")).unwrap()
}

fn example(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../schemas/examples").join(name);
    serde_json::from_str(&std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))).unwrap()
}

fn job_of(part: &Value) -> Value {
    let mut doc = example(part["base"].as_str().unwrap());
    for op in part["ops"].as_array().unwrap() {
        let path = op[0].as_array().unwrap();
        let (last, parents) = path.split_last().unwrap();
        let mut cur = &mut doc;
        for step in parents {
            cur = cur.get_mut(step.as_str().unwrap()).expect("the edit path exists");
        }
        let map = cur.as_object_mut().expect("an object");
        match op.get(1) {
            Some(v) => {
                map.insert(last.as_str().unwrap().to_string(), v.clone());
            }
            None => {
                map.remove(last.as_str().unwrap());
            }
        }
    }
    doc
}

fn run(part: &Value) -> (Value, Result<String, String>) {
    let job = job_of(part);
    let manifest: Vec<String> = part["manifest"].as_array().map(|l| l.iter().map(|x| x.as_str().unwrap().to_string()).collect()).unwrap_or_default();
    let out = kickstart(&job, part["label"].as_str().unwrap(), &manifest);
    (job, out)
}

fn after_first_line(text: &str) -> &str {
    text.split_once('\n').map(|(_, rest)| rest).unwrap_or("")
}

#[test]
fn every_case_matches_powershell() {
    let golden: Value = serde_json::from_str(include_str!("golden.json")).unwrap();
    let cases = cases();
    assert_eq!(golden.as_object().unwrap().len(), cases.len(), "golden.json is stale: run ./port-check.sh --record");
    let mut wrong = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().unwrap();
        for (i, part) in case["parts"].as_array().unwrap().iter().enumerate() {
            let want = &golden[name][i];
            let (_, got) = run(part);
            match (want.get("text").and_then(Value::as_str), want.get("refused").and_then(Value::as_str), &got) {
                (Some(ps), _, Ok(rust)) => {
                    assert!(ps.starts_with("# upgrade_ kickstart - generated by New-Kickstart.ps1 "));
                    assert!(rust.starts_with("# upgrade_ kickstart - generated by upgrade-kickstart "));
                    if after_first_line(ps) != after_first_line(rust) {
                        let at = ps.lines().zip(rust.lines()).skip(1).position(|(a, b)| a != b);
                        wrong.push(format!("FAIL  {name} (part {i}): the text differs at line {:?}\n  PowerShell: {:?}\n  Rust:       {:?}", at.map(|n| n + 2), at.and_then(|n| ps.lines().nth(n + 1)), at.and_then(|n| rust.lines().nth(n + 1))));
                    }
                }
                (_, Some(ps), Err(rust)) => {
                    if ps != rust {
                        wrong.push(format!("FAIL  {name} (part {i}): refused in other words\n  PowerShell: {ps}\n  Rust:       {rust}"));
                    }
                }
                _ => wrong.push(format!("FAIL  {name} (part {i}): PowerShell {want}, Rust {got:?}")),
            }
        }
    }
    assert!(wrong.is_empty(), "{} differ from New-Kickstart.ps1:\n\n{}", wrong.len(), wrong.join("\n\n"));
}

/// The PowerShell self-test's own assertions, held here directly.
#[test]
fn the_self_test_expectations_hold() {
    let mut wrong = Vec::new();
    let mut counted = 0;
    for case in cases().iter().filter(|c| c["origin"] == "selftest") {
        counted += 1;
        let name = case["name"].as_str().unwrap();
        for part in case["parts"].as_array().unwrap() {
            let (job, got) = run(part);
            let hash = job.pointer("/intent/account/password_hash").and_then(Value::as_str).unwrap_or("").to_string();
            for a in part["asserts"].as_array().expect("a self-test case asserts something") {
                let kind = a[0].as_str().unwrap();
                let arg = |n: usize| a[n].as_str().unwrap().replace("{password_hash}", &hash);
                let text = got.clone().unwrap_or_default();
                let lines: Vec<&str> = text.split('\n').collect();
                let holds = match kind {
                    "ok" => got.as_ref().is_ok_and(|t| !t.is_empty()),
                    "refused" => got.is_err(),
                    "line" => lines.contains(&arg(1).as_str()),
                    "line_prefix" => lines.iter().any(|l| l.starts_with(&arg(1))),
                    "line_suffix" => lines.iter().any(|l| l.ends_with(&arg(1))),
                    "no_line_prefix" => got.is_ok() && !lines.iter().any(|l| l.starts_with(&arg(1))),
                    "contains" => text.contains(&arg(1)),
                    "not_contains" => got.is_ok() && !text.contains(&arg(1)),
                    "before" => matches!((text.find(&arg(1)), text.find(&arg(2))), (Some(x), Some(y)) if x < y),
                    other => panic!("cases.json uses an assertion this test does not know: {other}"),
                };
                if !holds {
                    wrong.push(format!("FAIL  {name}: {a}"));
                }
            }
        }
    }
    assert!(counted >= 22, "only {counted} self-test cases in cases.json");
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

#[test]
fn the_checked_way_in_takes_only_a_job_that_passed_the_contract() {
    for name in ["job.keep-windows.json", "job.clean-slate.json", "job.erase-and-install.json", "job.acknowledged-data-loss.json"] {
        let job = Job::from_value(example(name)).unwrap();
        let ks = kickstart_for(&job, "UPGV0", &[]).unwrap();
        assert!(ks.ends_with("%end\n") && !ks.contains('\r'), "{name}");
    }
    // PowerShell's own checks let `JOB/1` through; the contract does not
    let mut loose = example("job.keep-windows.json");
    loose["schema"] = "JOB/1".into();
    assert!(kickstart(&loose, "UPGV0", &[]).is_ok());
    assert!(Job::from_value(loose).is_err());
}
